spring.application.name=rag
spring.ai.openai.api-key=${openai_api_key}
spring.ai.openai.chat.options.model=gpt-4

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

spring.docker.compose.lifecycle-management=start_only

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

